// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Entities.Models.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("LATITUDE");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("SUMMARY");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("double")
                        .HasColumnName("TEMPERATURE_C");

                    b.Property<double>("TemperatureF")
                        .HasColumnType("double")
                        .HasColumnName("TEMPERATURE_F");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("date")
                        .HasColumnName("DATETIME");

                    b.HasKey("Id");

                    b.ToTable("WEATHER");
                });
#pragma warning restore 612, 618
        }
    }
}
